# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\JetBrains\CLion 2021.2.1\bin\cmake\win\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\JetBrains\CLion 2021.2.1\bin\cmake\win\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\NITRO\CLionProjects\CPPExercises2021(1)

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\NITRO\CLionProjects\CPPExercises2021(1)

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	echo >nul && "C:\Program Files\JetBrains\CLion 2021.2.1\bin\cmake\win\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache\fast: edit_cache
.PHONY : edit_cache\fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	echo >nul && "C:\Program Files\JetBrains\CLion 2021.2.1\bin\cmake\win\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache\fast: rebuild_cache
.PHONY : rebuild_cache\fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\NITRO\CLionProjects\CPPExercises2021(1)\CMakeFiles C:\Users\NITRO\CLionProjects\CPPExercises2021(1)\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\NITRO\CLionProjects\CPPExercises2021(1)\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clean
.PHONY : clean

# The main clean target
clean\fast: clean
.PHONY : clean\fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall\fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) gtest
.PHONY : gtest

# fast build rule for target.
gtest\fast:
	$(MAKE) $(MAKESILENT) -f libs\3rdparty\libgtest\googletest\CMakeFiles\gtest.dir\build.make /nologo -$(MAKEFLAGS) libs\3rdparty\libgtest\googletest\CMakeFiles\gtest.dir\build
.PHONY : gtest\fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main\fast:
	$(MAKE) $(MAKESILENT) -f libs\3rdparty\libgtest\googletest\CMakeFiles\gtest_main.dir\build.make /nologo -$(MAKEFLAGS) libs\3rdparty\libgtest\googletest\CMakeFiles\gtest_main.dir\build
.PHONY : gtest_main\fast

#=============================================================================
# Target rules for targets named libutils

# Build rule for target.
libutils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) libutils
.PHONY : libutils

# fast build rule for target.
libutils\fast:
	$(MAKE) $(MAKESILENT) -f libs\utils\CMakeFiles\libutils.dir\build.make /nologo -$(MAKEFLAGS) libs\utils\CMakeFiles\libutils.dir\build
.PHONY : libutils\fast

#=============================================================================
# Target rules for targets named hello

# Build rule for target.
hello: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) hello
.PHONY : hello

# fast build rule for target.
hello\fast:
	$(MAKE) $(MAKESILENT) -f lesson01\CMakeFiles\hello.dir\build.make /nologo -$(MAKEFLAGS) lesson01\CMakeFiles\hello.dir\build
.PHONY : hello\fast

#=============================================================================
# Target rules for targets named lesson01_tests

# Build rule for target.
lesson01_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) lesson01_tests
.PHONY : lesson01_tests

# fast build rule for target.
lesson01_tests\fast:
	$(MAKE) $(MAKESILENT) -f lesson01\CMakeFiles\lesson01_tests.dir\build.make /nologo -$(MAKEFLAGS) lesson01\CMakeFiles\lesson01_tests.dir\build
.PHONY : lesson01_tests\fast

#=============================================================================
# Target rules for targets named lesson02vector

# Build rule for target.
lesson02vector: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) lesson02vector
.PHONY : lesson02vector

# fast build rule for target.
lesson02vector\fast:
	$(MAKE) $(MAKESILENT) -f lesson02\CMakeFiles\lesson02vector.dir\build.make /nologo -$(MAKEFLAGS) lesson02\CMakeFiles\lesson02vector.dir\build
.PHONY : lesson02vector\fast

#=============================================================================
# Target rules for targets named lesson03greenscreen

# Build rule for target.
lesson03greenscreen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) lesson03greenscreen
.PHONY : lesson03greenscreen

# fast build rule for target.
lesson03greenscreen\fast:
	$(MAKE) $(MAKESILENT) -f lesson03\CMakeFiles\lesson03greenscreen.dir\build.make /nologo -$(MAKEFLAGS) lesson03\CMakeFiles\lesson03greenscreen.dir\build
.PHONY : lesson03greenscreen\fast

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... gtest
	@echo ... gtest_main
	@echo ... hello
	@echo ... lesson01_tests
	@echo ... lesson02vector
	@echo ... lesson03greenscreen
	@echo ... libutils
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

